/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/layout/Breadcrumb.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ChatPanel: typeof import('./src/components/layout/ChatPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainPanel: typeof import('./src/components/layout/MainPanel.vue')['default']
    MarketOverview: typeof import('./src/components/home/MarketOverview.vue')['default']
    NewsCard: typeof import('./src/components/home/NewsCard.vue')['default']
    QuickActions: typeof import('./src/components/home/QuickActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/home/SearchBar.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TopToolbar: typeof import('./src/components/layout/TopToolbar.vue')['default']
    UpdateCard: typeof import('./src/components/home/UpdateCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
