name: 🐛 Bug Report
description: Report a bug in the Q-Ants application
title: "🐛 [Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - estebanmarinramirez

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to report a bug! 🐜
        
        Please fill out the sections below to help us understand and reproduce the issue.
        
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Please search for existing issues before creating a new one
      options:
        - label: I have searched existing issues
          required: true
        
  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which part of the application is affected?
      options:
        - Sidebar Navigation
        - Main Dashboard
        - Chat Panel
        - Charts/Visualization
        - Portfolio Management
        - Task Management
        - Settings/Configuration
        - Authentication
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior...
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      value: |
        - OS: [e.g. macOS 14.4.0]
        - Browser: [e.g. Chrome 126, Safari 17]
        - Node.js: [e.g. 20.15.0]
        - Vue.js: [e.g. 3.5.13]
        - PrimeVue: [e.g. 4.3.4]
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Console Logs
      description: If applicable, add screenshots or console error logs
      placeholder: Paste screenshots or error logs here...
      
  - type: checkboxes
    id: urgency
    attributes:
      label: Urgency Level
      options:
        - label: 🔥 Critical (Application breaks/security issue)
        - label: 🚨 High (Major feature not working)  
        - label: ⚠️ Medium (Minor feature issue)
        - label: 📝 Low (Cosmetic/Enhancement) 