name: ✨ Feature Request
description: Suggest a new feature for the Q-Ants application
title: "✨ [Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - estebanmarinramirez

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature! 🚀
        
        Please fill out the sections below to help us understand your feature request.
        
  - type: checkboxes
    id: existing-features
    attributes:
      label: Existing Features
      description: Please check if this feature already exists
      options:
        - label: I have searched existing features and issues
          required: true
        
  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which part of the application would this feature affect?
      options:
        - Sidebar Navigation
        - Main Dashboard
        - Chat Panel
        - Charts/Visualization
        - Portfolio Management
        - Task Management
        - Settings/Configuration
        - Authentication
        - PrimeVue Integration
        - Sakai Template Features
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or pain point this feature would address...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: Clearly describe your proposed feature...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions you've considered...
      
  - type: dropdown
    id: primevue-component
    attributes:
      label: PrimeVue Component
      description: Could this feature leverage existing PrimeVue components?
      options:
        - "Not applicable"
        - "DataTable"
        - "Chart"
        - "Menu/Sidebar"
        - "TabView"
        - "Dialog"
        - "Toast/Messages"
        - "FileUpload"
        - "MultiSelect"
        - "Calendar"
        - "TreeTable"
        - "Panel"
        - "Other PrimeVue component"
        
  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If applicable, add mockups or wireframes
      placeholder: Paste images or links to designs here...
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - "🔥 High (Critical for workflow)"
        - "⚠️ Medium (Would be very helpful)"
        - "📝 Low (Nice to have)"
    validations:
      required: true
      
  - type: dropdown
    id: effort
    attributes:
      label: Implementation Effort (estimate)
      description: How complex do you think this feature would be to implement?
      options:
        - "🟢 Low (Few hours)"
        - "🟡 Medium (1-2 days)"  
        - "🟠 High (1+ weeks)"
        - "🔴 Very High (Major refactor)"
        - "❓ Unknown"
        
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
        - label: I can provide additional mockups/designs
        - label: I can help with testing this feature 